spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nexpin
    username: postgres
    password: Aytc7mDl
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect